version: "3"
services:
    postgres:
        container_name: postgres
        image: "postgres:latest"
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - /data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
    front:
        container_name: front
        build:
            context: ./client/
        volumes:
            - "./client:/usr/front"
            - "/usr/front/node_modules"
        ports:
            - "3000:3000"
    backend:
        container_name: backend
        build:
            context: ./Server/
        ports:
            - "3333:3333"
        volumes:
            - "./Server:/usr/backend"
            - "/usr/backend/node_modules"
        environment:
            - PORT=3333
            - CORES=2
            - DB_HOST=postgres
            - DB_USERNAME=root
            - DB_PASSWORD=root
        links:
            - postgres
        depends_on:
            - postgres
        command: su -c './wait-for-it.sh'
